const database = require('./database/DbBlog')

// Cria tabela artigos, caso ela não exista...
const ArtigosEntity = require('./tabelas/ArtigosEntity')
// Definir uma nova tabela...
// Criar recursos de consulta para essa tabela...

try {
    // Tenta autenticar...
    database.authenticate();
    // Se autenticação acontecer, sincroniza com banco...
    database.sync();
}
catch(error) {
    // Caso aconteça algum erro, retorna o erro para usuário...
    console.error(error);
}